=== jakub94/WebDevelopment/sitemap.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:complexType name="sitemapType">
		<xs:sequence>
			<xs:element name="page" type="pageType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="pageType">
		<xs:sequence minOccurs="1" maxOccurs="unbounded">
			<xs:element name="name" type="xs:string"/>
			<xs:element name="link" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" use="required" type="xs:integer"/>
		<xs:attribute name="parentId" type="xs:integer"/>
	</xs:complexType>
	
	<xs:element name="sitemap" type="sitemapType"/>

</xs:schema>

=== jakub94/WebDevelopment/sitemap.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<sitemap xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="sitemap.xsd">

	<page id="1">
		<name>Hello</name>
		<link>index.html</link>
	</page>

	<page id="2">
		<name>Team</name>
		<link>content/team.html</link>
	</page>

	<page id="3">
		<name>Coding Standards</name>
		<link>content/coding_standards.html</link>
	</page>

	<page id="4">
		<name>Game</name>
		<link>content/game.html</link>
	</page>

	<page id="5">
		<name>About Us</name>
		<link>content/about_us.html</link>
	</page>

	<page id="6">
		<name>Contact</name>
		<link>content/contact.html</link>
	</page>

</sitemap>
